
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DLL.DATA.SeguridadSoluinfo
{

using System;
    using System.Collections.Generic;
    
public partial class BITACORA_MOVIMIENTOS
{

    public int ID_BITACORA { get; set; }

    public int ID_HORARIO_CONDUCTOR { get; set; }

    public int ID_TIPO_MOVIMIENTO { get; set; }

    public bool ESTADO { get; set; }



    public virtual TIPO_MOVIEMIENTO_HORARIO TIPO_MOVIEMIENTO_HORARIO { get; set; }

}

}
