//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.DATA.SeguridadSoluinfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARGA_HORARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARGA_HORARIO()
        {
            this.HORARIO_CONDUCTOR = new HashSet<HORARIO_CONDUCTOR>();
        }
    
        public int ID_CARGA_HORARIO { get; set; }
        public int ID_USUARIO_CARGA { get; set; }
        public string NOMBRE_CARGA { get; set; }
        public string COMENTARIO_CARGA { get; set; }
        public System.DateTime FECHA_CARGA { get; set; }
        public bool ESTADO { get; set; }
        public Nullable<short> NUMERO_JORNADA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HORARIO_CONDUCTOR> HORARIO_CONDUCTOR { get; set; }
        public virtual USUARIOS_SISTEMA USUARIOS_SISTEMA { get; set; }
    }
}
