//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.DATA.SeguridadSoluinfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class HORARIO_CONDUCTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HORARIO_CONDUCTOR()
        {
            this.SERVICIO_REALIZADO = new HashSet<SERVICIO_REALIZADO>();
        }
    
        public int ID_HORARIO { get; set; }
        public int ID_CARGA_HORARIO { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_TERMINAL_INICIO { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public bool HORARIO_CUBIERTO { get; set; }
        public Nullable<int> ID_BUS_INICIO { get; set; }
        public bool ESTADO { get; set; }
        public short NUMERO_JORNADA { get; set; }
    
        public virtual CARGA_HORARIO CARGA_HORARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIO_REALIZADO> SERVICIO_REALIZADO { get; set; }
    }
}
