
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DLL.DATA.SeguridadSoluinfo
{

using System;
    using System.Collections.Generic;
    
public partial class NOVEDADES
{

    public byte ORDEN { get; set; }

    public string TITULO { get; set; }

    public string DESCRIPCION { get; set; }

    public byte ID_TIPO_NOVEDAD { get; set; }

    public short ID_PROYECTO { get; set; }



    public virtual PROYECTOS PROYECTOS { get; set; }

    public virtual TIPOS_NOVEDADES TIPOS_NOVEDADES { get; set; }

}

}
