
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DLL.DATA.SeguridadSoluinfo
{

using System;
    using System.Collections.Generic;
    
public partial class PARAMETROS
{

    public int ID_PARAMETRO { get; set; }

    public string NOMBRE_PARAMETRO { get; set; }

    public string DESCRIPCION_PARAMATRO { get; set; }

    public string VALOR_1 { get; set; }

    public string VALOR_2 { get; set; }

    public Nullable<bool> VALOR_3 { get; set; }

    public bool ESTADO { get; set; }

}

}
