
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DLL.DATA.SeguridadSoluinfo
{

using System;
    using System.Collections.Generic;
    
public partial class PERFILES
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PERFILES()
    {

        this.ACCIONES = new HashSet<ACCIONES>();

        this.USUARIOS_SISTEMA = new HashSet<USUARIOS_SISTEMA>();

    }


    public short ID_PERFIL { get; set; }

    public short ID_AREA { get; set; }

    public string NOMBRE { get; set; }

    public bool ESTADO { get; set; }



    public virtual AREAS AREAS { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ACCIONES> ACCIONES { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<USUARIOS_SISTEMA> USUARIOS_SISTEMA { get; set; }

}

}
