//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.DATA.SeguridadSoluinfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISOS_ESPECIALES
    {
        public int ID_USUARIO { get; set; }
        public int ID_ACCION { get; set; }
        public short ID_PROYECTO { get; set; }
        public bool TIPO_PERMISO { get; set; }
    
        public virtual ACCIONES ACCIONES { get; set; }
        public virtual PROYECTOS PROYECTOS { get; set; }
        public virtual USUARIOS_SISTEMA USUARIOS_SISTEMA { get; set; }
    }
}
