//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.DATA.SeguridadSoluinfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROYECTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROYECTOS()
        {
            this.PERMISOS_ESPECIALES = new HashSet<PERMISOS_ESPECIALES>();
            this.VERSION_PROYECTO = new HashSet<VERSION_PROYECTO>();
            this.PROYECTO_AGRUPACION = new HashSet<PROYECTO_AGRUPACION>();
            this.AREAS = new HashSet<AREAS>();
            this.NOVEDADES = new HashSet<NOVEDADES>();
            this.MENU = new HashSet<MENU>();
        }
    
        public short ID_PROYECTO { get; set; }
        public byte ID_PLATAFORMA { get; set; }
        public string NOMBRE_INTERNO { get; set; }
        public string NOMBRE_VISIBLE { get; set; }
        public string PAGINA_INICIO { get; set; }
        public string URL_PROYECTO { get; set; }
        public string ICON_UNO { get; set; }
        public string ICON_DOS { get; set; }
        public System.DateTime FECHA_VERSION { get; set; }
        public string VERSION { get; set; }
        public bool ESTADO { get; set; }
    
        public virtual PLATAFORMAS PLATAFORMAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERMISOS_ESPECIALES> PERMISOS_ESPECIALES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VERSION_PROYECTO> VERSION_PROYECTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROYECTO_AGRUPACION> PROYECTO_AGRUPACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AREAS> AREAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOVEDADES> NOVEDADES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENU> MENU { get; set; }
    }
}
