//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.DATA.SeguridadSoluinfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_HORARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REGISTRO_HORARIO()
        {
            this.REGISTRO_VUELTAS = new HashSet<REGISTRO_VUELTAS>();
        }
    
        public int ID_REGISTRO_HORARIO { get; set; }
        public int ID_HORARIO { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_TERMINAL_INICIO { get; set; }
        public System.DateTime FECHA_HORA_INICIO { get; set; }
        public Nullable<int> ID_TERMINAL_FIN { get; set; }
        public Nullable<System.DateTime> FECHA_HORA_FIN { get; set; }
        public bool ESTADO { get; set; }
    
        public virtual USUARIOS_SISTEMA USUARIOS_SISTEMA { get; set; }
        public virtual HORARIO_CONDUCTOR HORARIO_CONDUCTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_VUELTAS> REGISTRO_VUELTAS { get; set; }
    }
}
