
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DLL.DATA.SeguridadSoluinfo
{

using System;
    using System.Collections.Generic;
    
public partial class SERVICIO_REALIZADO
{

    public int ID_RECORRIDO { get; set; }

    public int ID_HORARIO { get; set; }

    public int ID_TERMINAL { get; set; }

    public int ID_SERVICIO { get; set; }

    public int ID_SENTIDO { get; set; }

    public int ID_USUARIO { get; set; }

    public System.DateTime HORA_INICIO { get; set; }

    public Nullable<System.DateTime> HORA_FIN { get; set; }

    public Nullable<int> ID_BUS { get; set; }

    public bool ESTADO { get; set; }

    public Nullable<System.TimeSpan> HORAS_EXTRAS { get; set; }



    public virtual BUS BUS { get; set; }

    public virtual SENTIDO SENTIDO { get; set; }

    public virtual TERMINAL TERMINAL { get; set; }

    public virtual HORARIO_CONDUCTOR HORARIO_CONDUCTOR { get; set; }

    public virtual USUARIOS_SISTEMA USUARIOS_SISTEMA { get; set; }

    public virtual SERVICIO SERVICIO { get; set; }

}

}
