//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.DATA.SeguridadSoluinfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICIO()
        {
            this.SERVICIO_REALIZADO = new HashSet<SERVICIO_REALIZADO>();
        }
    
        public int ID_SERVICIO { get; set; }
        public int ID_EMPRESA { get; set; }
        public string NOMBRE_SERVICIO { get; set; }
        public Nullable<System.TimeSpan> HORARIO_INICIO_SERVICO { get; set; }
        public Nullable<System.TimeSpan> HORARIO_FIN_SERVICO { get; set; }
        public bool ESTADO { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIO_REALIZADO> SERVICIO_REALIZADO { get; set; }
    }
}
