//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.DATA.SeguridadSoluinfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_MOVIEMIENTO_HORARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_MOVIEMIENTO_HORARIO()
        {
            this.BITACORA_MOVIMIENTOS = new HashSet<BITACORA_MOVIMIENTOS>();
        }
    
        public int ID_TIPO_MOVIMIENTO { get; set; }
        public string NOMBRE_MOVIMEINTO { get; set; }
        public bool ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BITACORA_MOVIMIENTOS> BITACORA_MOVIMIENTOS { get; set; }
    }
}
