
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DLL.DATA.SeguridadSoluinfo
{

using System;
    using System.Collections.Generic;
    
public partial class TIPOS_NOVEDADES
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TIPOS_NOVEDADES()
    {

        this.NOVEDADES = new HashSet<NOVEDADES>();

    }


    public byte ID_TIPO_NOVEDAD { get; set; }

    public Nullable<int> ID_VERSION { get; set; }

    public string DESCRIPCION { get; set; }

    public string COLOR { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<NOVEDADES> NOVEDADES { get; set; }

}

}
