//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.DATA.SeguridadSoluinfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_SOLICITUD_CAMBIO
    {
        public int ID_TIPO_SOLICITUD { get; set; }
        public string NOMBRE_SOLICITUD { get; set; }
        public bool ESTADO { get; set; }
    }
}
