
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DLL.DATA.SeguridadSoluinfo
{

using System;
    using System.Collections.Generic;
    
public partial class VERSION_PROYECTO
{

    public int ID_VERSION { get; set; }

    public short ID_PROYECTO { get; set; }

    public Nullable<short> V1 { get; set; }

    public Nullable<short> V2 { get; set; }

    public Nullable<short> V3 { get; set; }

    public Nullable<short> V4 { get; set; }

    public Nullable<int> USER_CREACION { get; set; }

    public Nullable<System.DateTime> FECHA_CREACION { get; set; }

    public Nullable<int> USER_MODIFICA { get; set; }

    public Nullable<System.DateTime> FECHA_MODIFICA { get; set; }

    public Nullable<System.DateTime> FECHA_PUESTA_EN_MARCHA { get; set; }

    public bool ESTADO { get; set; }



    public virtual PROYECTOS PROYECTOS { get; set; }

}

}
